name: 'Terraform'
on: 
  push:
    branches: [ develop]
  pull_request:
    branches: [ develop]
# env:
#   TF_LOG: INFO
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    # environment: dev

defaults:
  run:
    working-directory: ./
    shell: bash
    

  steps:

     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
       cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
       terraform_version: 1.0.4

     - name: Terraform Init
       run: terraform init -reconfigure -backend-config="address=https://s3.console.aws.amazon.com/s3/object/mojec-tf-backend?region=eu-west-2&prefix=mojec/state/backup"

     - name: Terraform Plan
       run: terraform plan -var-file=env/dev/terraform.tfvars

     - name: Terraform Apply 
       if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
       run: terraform apply  -var-file=env/dev/terraform.tfvars -auto-approve

     - name: kubeuserauth
        run:|
        - aws eks update-kubeconfig --region eu-west-1 --name Beta_${CI_COMMIT_BRANCH}_eks_cluster
        - kubectl apply -f kube-auth/cluster-role.yml
        - kubectl apply -f kube-auth/cluster-rolebinding.yml
        - kubectl apply -f kube-auth/aws-auth.yml